apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: superiad
build:
  artifacts:
  - image: 816119410753.dkr.ecr.us-east-2.amazonaws.com/flexable-superiad
    docker:
      dockerfile: Dockerfile
deploy:
  helm:
    releases:
    - name: flexable-superiad
      namespace: flexable
      repo: https://thelazarusnetwork.github.io/lazarus-k8s
      remoteChart: deployment
      version: 0.1.4
      artifactOverrides:
        image: 816119410753.dkr.ecr.us-east-2.amazonaws.com/flexable-superiad
      imageStrategy:
        helm: {}
      valuesFiles:
        - "values.yml"