name: "[DEV] Build and Push to GHCR"

on:
  push:
    branches: [ "main" ]

jobs:

  main:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}
    
    - name: Build and Push Docker Image
      run: |
        export CURRENT_BRANCH=${GITHUB_REF#refs/heads/}
        export TAG=$([[ $CURRENT_BRANCH == "main" ]] && echo $CURRENT_BRANCH || echo "latest")
        export GITHUB_REF_IMAGE=ghcr.io/$GITHUB_REPOSITORY:$GITHUB_SHA
        export GITHUB_BRANCH_IMAGE=ghcr.io/$GITHUB_REPOSITORY:$TAG
        docker build -t $GITHUB_REF_IMAGE -t $GITHUB_BRANCH_IMAGE .
        echo "Pushing Image to GitHub Container Registry"
        docker push $GITHUB_REF_IMAGE
        docker push $GITHUB_BRANCH_IMAGE
    